<?php

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-04-28 09:48:41',
                'updated_at' => '2020-04-28 09:48:41',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-04-28 09:48:41',
                'updated_at' => '2020-04-28 09:48:41',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerRoleController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-04-28 09:48:41',
                'updated_at' => '2020-04-28 09:48:41',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'categories',
                'slug' => 'categories',
                'display_name_singular' => 'Category',
                'display_name_plural' => 'Categories',
                'icon' => 'voyager-categories',
                'model_name' => 'TCG\\Voyager\\Models\\Category',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'created_at' => '2020-04-28 09:48:48',
                'updated_at' => '2020-07-26 07:53:27',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'posts',
                'slug' => 'posts',
                'display_name_singular' => 'Post',
                'display_name_plural' => 'Posts',
                'icon' => 'voyager-news',
                'model_name' => 'TCG\\Voyager\\Models\\Post',
                'policy_name' => 'TCG\\Voyager\\Policies\\PostPolicy',
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":"title","scope":null}',
                'created_at' => '2020-04-28 09:48:49',
                'updated_at' => '2020-05-03 14:37:43',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'pages',
                'slug' => 'pages',
                'display_name_singular' => 'Page',
                'display_name_plural' => 'Pages',
                'icon' => 'voyager-file-text',
                'model_name' => 'TCG\\Voyager\\Models\\Page',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-04-28 09:48:50',
                'updated_at' => '2020-04-28 09:48:50',
            ),
            6 => 
            array (
                'id' => 16,
                'name' => 'testimonials',
                'slug' => 'testimonials',
                'display_name_singular' => 'Testimonial',
                'display_name_plural' => 'Testimonials',
                'icon' => 'voyager-star',
                'model_name' => 'App\\Testimonial',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-06-18 15:28:07',
                'updated_at' => '2020-06-21 05:15:50',
            ),
            7 => 
            array (
                'id' => 18,
                'name' => 'members',
                'slug' => 'members',
                'display_name_singular' => 'Member',
                'display_name_plural' => 'Members',
                'icon' => 'voyager-people',
                'model_name' => 'App\\Member',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":"name"}',
                'created_at' => '2020-06-18 15:40:58',
                'updated_at' => '2020-06-18 15:40:58',
            ),
            8 => 
            array (
                'id' => 19,
                'name' => 'brands',
                'slug' => 'brands',
                'display_name_singular' => 'Brand',
                'display_name_plural' => 'Brands',
                'icon' => 'voyager-tag',
                'model_name' => 'App\\Brand',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":"name"}',
                'created_at' => '2020-06-20 05:07:56',
                'updated_at' => '2020-06-20 05:07:56',
            ),
            9 => 
            array (
                'id' => 20,
                'name' => 'products',
                'slug' => 'products',
                'display_name_singular' => 'Product',
                'display_name_plural' => 'Products',
                'icon' => 'voyager-bag',
                'model_name' => 'App\\Product',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":"title","scope":null}',
                'created_at' => '2020-06-24 16:19:26',
                'updated_at' => '2020-07-26 07:54:05',
            ),
            10 => 
            array (
                'id' => 21,
                'name' => 'coupons',
                'slug' => 'coupons',
                'display_name_singular' => 'Coupon',
                'display_name_plural' => 'Coupons',
                'icon' => 'voyager-dollar',
                'model_name' => 'App\\Coupon',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":"title","scope":null}',
                'created_at' => '2020-06-26 08:53:11',
                'updated_at' => '2020-06-26 09:00:11',
            ),
            11 => 
            array (
                'id' => 22,
                'name' => 'orders',
                'slug' => 'orders',
                'display_name_singular' => 'Order',
                'display_name_plural' => 'Orders',
                'icon' => 'voyager-bag',
                'model_name' => 'App\\Order',
                'policy_name' => NULL,
                'controller' => 'App\\Http\\Controllers\\Voyager\\OrdersController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":"invoice_id","scope":null}',
                'created_at' => '2020-06-27 08:37:04',
                'updated_at' => '2020-07-26 06:57:23',
            ),
            12 => 
            array (
                'id' => 23,
                'name' => 'customers',
                'slug' => 'customers',
                'display_name_singular' => 'Customer',
                'display_name_plural' => 'Customers',
                'icon' => 'voyager-people',
                'model_name' => 'App\\Customer',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-06-30 05:29:08',
                'updated_at' => '2020-07-26 06:56:15',
            ),
            13 => 
            array (
                'id' => 24,
                'name' => 'reviews',
                'slug' => 'reviews',
                'display_name_singular' => 'Review',
                'display_name_plural' => 'Reviews',
                'icon' => 'voyager-star',
                'model_name' => 'App\\Review',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":"product_id","scope":null}',
                'created_at' => '2020-07-01 10:43:56',
                'updated_at' => '2020-07-01 10:48:21',
            ),
            14 => 
            array (
                'id' => 25,
                'name' => 'currencies',
                'slug' => 'currencies',
                'display_name_singular' => 'Currency',
                'display_name_plural' => 'Currencies',
                'icon' => 'voyager-credit-cards',
                'model_name' => 'App\\Currency',
                'policy_name' => NULL,
                'controller' => 'App\\Http\\Controllers\\Voyager\\CurrencyController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":"name","scope":null}',
                'created_at' => '2020-07-01 15:55:45',
                'updated_at' => '2020-07-02 10:02:42',
            ),
        ));
        
        
    }
}