<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-04-28 09:48:42',
                'updated_at' => '2020-07-25 12:47:11',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2020-04-28 09:48:42',
                'updated_at' => '2020-06-20 15:38:37',
                'route' => 'voyager.media.index',
                'parameters' => 'null',
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2020-04-28 09:48:42',
                'updated_at' => '2020-04-28 09:48:42',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2020-04-28 09:48:42',
                'updated_at' => '2020-04-28 09:48:42',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2020-04-28 09:48:42',
                'updated_at' => '2020-07-25 15:38:56',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2020-04-28 09:48:42',
                'updated_at' => '2020-05-03 15:34:55',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2020-04-28 09:48:42',
                'updated_at' => '2020-05-03 15:34:55',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2020-04-28 09:48:42',
                'updated_at' => '2020-05-03 15:34:55',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2020-04-28 09:48:42',
                'updated_at' => '2020-05-03 15:34:55',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2020-04-28 09:48:42',
                'updated_at' => '2020-07-25 15:38:56',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2020-04-28 09:48:48',
                'updated_at' => '2020-07-05 07:03:45',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2020-04-28 09:48:49',
                'updated_at' => '2020-07-05 07:03:44',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2020-04-28 09:48:50',
                'updated_at' => '2020-07-05 07:03:44',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2020-04-28 09:48:52',
                'updated_at' => '2020-05-03 15:34:55',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 18,
                'menu_id' => 2,
                'title' => 'Home',
                'url' => '/',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-05-01 11:27:01',
                'updated_at' => '2020-05-01 11:31:42',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 19,
                'menu_id' => 2,
                'title' => 'News',
                'url' => '/posts',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2020-05-01 11:28:27',
                'updated_at' => '2020-07-05 07:09:21',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 22,
                'menu_id' => 2,
                'title' => 'Contact',
                'url' => '/contact',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2020-05-02 11:26:09',
                'updated_at' => '2020-07-05 07:09:21',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 23,
                'menu_id' => 3,
                'title' => 'Privacy Policy',
                'url' => '/page/privacy-policy',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-05-03 10:44:22',
                'updated_at' => '2020-06-20 16:00:25',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 24,
                'menu_id' => 3,
                'title' => 'Terms & Condition',
                'url' => '/page/terms-condition',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2020-05-03 10:45:11',
                'updated_at' => '2020-06-20 16:00:25',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 25,
                'menu_id' => 3,
                'title' => 'Contact',
                'url' => '/contact',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2020-05-03 10:47:16',
                'updated_at' => '2020-06-20 16:00:25',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Testimonials',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-star',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2020-06-18 15:28:07',
                'updated_at' => '2020-07-25 15:39:09',
                'route' => 'voyager.testimonials.index',
                'parameters' => NULL,
            ),
            21 => 
            array (
                'id' => 35,
                'menu_id' => 2,
                'title' => 'About',
                'url' => '/about',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2020-06-18 15:32:03',
                'updated_at' => '2020-07-05 07:09:21',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => 37,
                'menu_id' => 1,
                'title' => 'Members',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2020-06-18 15:40:58',
                'updated_at' => '2020-07-25 15:39:09',
                'route' => 'voyager.members.index',
                'parameters' => NULL,
            ),
            23 => 
            array (
                'id' => 38,
                'menu_id' => 1,
                'title' => 'Brands',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2020-06-20 05:07:57',
                'updated_at' => '2020-07-25 15:39:09',
                'route' => 'voyager.brands.index',
                'parameters' => NULL,
            ),
            24 => 
            array (
                'id' => 39,
                'menu_id' => 3,
                'title' => 'Terms of Service',
                'url' => '#',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2020-06-20 16:00:21',
                'updated_at' => '2020-06-20 16:00:25',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 40,
                'menu_id' => 1,
                'title' => 'Products',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2020-06-24 16:19:27',
                'updated_at' => '2020-07-25 15:38:55',
                'route' => 'voyager.products.index',
                'parameters' => NULL,
            ),
            26 => 
            array (
                'id' => 41,
                'menu_id' => 1,
                'title' => 'Coupons',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dollar',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2020-06-26 08:53:11',
                'updated_at' => '2020-07-25 15:39:09',
                'route' => 'voyager.coupons.index',
                'parameters' => NULL,
            ),
            27 => 
            array (
                'id' => 42,
                'menu_id' => 1,
                'title' => 'Orders',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2020-06-27 08:37:05',
                'updated_at' => '2020-07-25 15:38:59',
                'route' => 'voyager.orders.index',
                'parameters' => 'null',
            ),
            28 => 
            array (
                'id' => 43,
                'menu_id' => 1,
                'title' => 'Customers',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2020-06-30 05:29:08',
                'updated_at' => '2020-07-25 15:39:09',
                'route' => 'voyager.customers.index',
                'parameters' => NULL,
            ),
            29 => 
            array (
                'id' => 44,
                'menu_id' => 1,
                'title' => 'Reviews',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-star',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2020-07-01 10:43:57',
                'updated_at' => '2020-07-25 15:38:56',
                'route' => 'voyager.reviews.index',
                'parameters' => NULL,
            ),
            30 => 
            array (
                'id' => 45,
                'menu_id' => 1,
                'title' => 'Currencies',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-cards',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2020-07-01 15:55:45',
                'updated_at' => '2020-07-25 15:38:56',
                'route' => 'voyager.currencies.index',
                'parameters' => NULL,
            ),
            31 => 
            array (
                'id' => 46,
                'menu_id' => 2,
                'title' => 'Shop',
                'url' => '/shop',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2020-07-05 07:09:14',
                'updated_at' => '2020-07-05 07:09:21',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}